apiVersion: v1
kind: Service
metadata: 
   name: gowebapp
   labels:
     run: gowebapp
     tier: frontend
spec:
   ports:
   - port: 9000
     targetPort: 80
   selector:
     run: gowebapp
     tier: frontend
   type: LoadBalancer
