apiVersion: apps/v1beta1
kind: Deployment
metadata: 
   name: gowebapp-mysql
   labels:
     run: gowebapp-mysql
     tier: backend
spec:
   replicas: 1
   strategy: 
     type: Recreate
   template:
     metadata:
       labels:
         run: gowebapp-mysql
         tier: backend
     spec:
       containers:
       - env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom: 
              secretKeyRef:
                 name: mysql
                 key: password
         image: gcr.io/qwiklabs-gcp-17d9ccc736921024/gowebapp-mysql:v1
         name: gowebapp-mysql
         ports:
         - containerPort: 3306
         volumeMounts:
         - mountPaths: /var/lib/mysql
           name: mysql
         volumes:
 	 - name: mysql
           persistentVolumeClaim:
              claimName: mysqlpvc
